// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trellis.Assistant.Data;

#nullable disable

namespace Trellis.Assistant.Migrations
{
    [DbContext(typeof(AssistantDbContext))]
    [Migration("20260505130659_AddToolCallIdAndToolNameToTurns")]
    partial class AddToolCallIdAndToolNameToTurns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trellis.Assistant.Data.AgentRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("AssistantTurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("assistant_turn_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("TokensUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("tokens_used");

                    b.HasKey("Id");

                    b.HasIndex("AssistantTurnId");

                    b.HasIndex("OrgId", "StartedAt")
                        .HasDatabaseName("ix_agent_runs_org_id_started_at");

                    b.ToTable("agent_runs", (string)null);
                });

            modelBuilder.Entity("Trellis.Assistant.Data.AgentStepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("DurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("StepIndex")
                        .HasColumnType("integer")
                        .HasColumnName("step_index");

                    b.Property<string>("ToolInputJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_input_json");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tool_name");

                    b.Property<string>("ToolOutputJson")
                        .HasColumnType("text")
                        .HasColumnName("tool_output_json");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId", "StepIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_steps_run_step");

                    b.ToTable("agent_steps", (string)null);
                });

            modelBuilder.Entity("Trellis.Assistant.Data.ConversationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("api")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("mistral-small:24b")
                        .HasColumnName("model");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_conversations_tenant_user");

                    b.HasIndex("TenantId", "UserId", "Channel")
                        .HasDatabaseName("ix_conversations_tenant_user_channel");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Trellis.Assistant.Data.TurnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("ToolCallId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tool_call_id");

                    b.Property<string>("ToolName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_turns_conversation_position");

                    b.ToTable("turns", (string)null);
                });

            modelBuilder.Entity("Trellis.Assistant.Data.AgentRunEntity", b =>
                {
                    b.HasOne("Trellis.Assistant.Data.TurnEntity", null)
                        .WithMany()
                        .HasForeignKey("AssistantTurnId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Trellis.Assistant.Data.AgentStepEntity", b =>
                {
                    b.HasOne("Trellis.Assistant.Data.AgentRunEntity", null)
                        .WithMany()
                        .HasForeignKey("AgentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trellis.Assistant.Data.TurnEntity", b =>
                {
                    b.HasOne("Trellis.Assistant.Data.ConversationEntity", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
